def run_pixel(ctx, out):
    rt = ctx.rt
    U = ctx.uniforms
    T = ctx.textures
    class _G:
        pass
    g = _G()
    _u_MODE = U.get("MODE", 0)
    _u_inputTex = T["inputTex"]
    _u_resolution = U.get("resolution", rt.construct(2, 0.0))
    _u_tileOffset = U.get("tileOffset", rt.construct(2, 0.0))
    _u_tileSize = U.get("tileSize", rt.f(0.0))
    _u_groutWidth = U.get("groutWidth", rt.f(0.0))
    _u_relief = U.get("relief", rt.f(0.0))
    _u_maxOffset = U.get("maxOffset", rt.f(0.0))
    _u_gapFill = U.get("gapFill", 0)
    _u_backgroundColor = U.get("backgroundColor", rt.construct(3, 0.0))
    _u_seed = U.get("seed", 0)
    g.fragColor = rt.construct(4, 0.0)
    def hash12__vec2(p):
        p = rt.copy(p, "float")
        p3 = rt.component_wise("fract", rt.binary("*", rt.construct(3, rt.swizzle(p, "xyx")), rt.f(0.1031), 3, "float"), width=3)
        p3[:] = rt.binary("+", p3, rt.dot(p3, rt.binary("+", rt.swizzle(p3, "yzx"), rt.f(33.33), 3, "float")), 3, "float")
        return rt.component_wise("fract", rt.binary("*", rt.binary("+", rt.swizzle(p3, "x"), rt.swizzle(p3, "y"), 1, "float"), rt.swizzle(p3, "z"), 1, "float"), width=1)
    def hash22__vec2(p):
        p = rt.copy(p, "float")
        p3 = rt.component_wise("fract", rt.binary("*", rt.construct(3, rt.swizzle(p, "xyx")), rt.construct(3, rt.f(0.1031), rt.f(0.103), rt.f(0.0973)), 3, "float"), width=3)
        p3[:] = rt.binary("+", p3, rt.dot(p3, rt.binary("+", rt.swizzle(p3, "yzx"), rt.f(33.33), 3, "float")), 3, "float")
        return rt.component_wise("fract", rt.binary("*", rt.binary("+", rt.swizzle(p3, "xx"), rt.swizzle(p3, "yz"), 2, "float"), rt.swizzle(p3, "zy"), 2, "float"), width=2)
    def vnoise__vec2(p):
        p = rt.copy(p, "float")
        i = rt.component_wise("floor", p, width=2)
        f = rt.component_wise("fract", p, width=2)
        u = rt.binary("*", rt.binary("*", f, f, 2, "float"), rt.binary("-", rt.f(3.0), rt.binary("*", rt.f(2.0), f, 2, "float"), 2, "float"), 2, "float")
        return rt.component_wise("mix", rt.component_wise("mix", hash12__vec2(i), hash12__vec2(rt.binary("+", i, rt.construct(2, rt.f(1.0), rt.f(0.0)), 2, "float")), rt.swizzle(u, "x"), width=1), rt.component_wise("mix", hash12__vec2(rt.binary("+", i, rt.construct(2, rt.f(0.0), rt.f(1.0)), 2, "float")), hash12__vec2(rt.binary("+", i, rt.construct(2, rt.f(1.0), rt.f(1.0)), 2, "float")), rt.swizzle(u, "x"), width=1), rt.swizzle(u, "y"), width=1)
    def reliefShade__float_float_float_float_float(hC, hR, hT, strength, lightAngleDeg):
        grad = rt.binary("*", rt.construct(2, rt.binary("-", hR, hC, 1, "float"), rt.binary("-", hT, hC, 1, "float")), strength, 2, "float")
        n = rt.normalize(rt.construct(3, rt.unary("-", grad), rt.f(1.0)))
        a = rt.component_wise("radians", lightAngleDeg, width=1)
        L = rt.normalize(rt.construct(3, rt.component_wise("cos", a, width=1), rt.component_wise("sin", a, width=1), rt.f(0.75)))
        return rt.component_wise("clamp", rt.dot(n, L), rt.f(0.0), rt.f(1.0), width=1)
    def mosaicWarp__vec2_float_float(gc, tileSizePx, seedVal):
        gc = rt.copy(gc, "float")
        return rt.binary("*", rt.binary("*", vnoise__vec2(rt.binary("+", rt.binary("/", gc, tileSizePx, 2, "float"), rt.binary("*", seedVal, rt.f(101.7), 1, "float"), 2, "float")), rt.f(0.25), 1, "float"), tileSizePx, 1, "float")
    def mosaicGroutMask__vec2_float_float_float(gc, tileSizePx, groutWidthPct, seedVal):
        gc = rt.copy(gc, "float")
        warp = mosaicWarp__vec2_float_float(gc, tileSizePx, seedVal)
        cellFrac = rt.component_wise("fract", rt.binary("/", rt.binary("+", gc, rt.construct(2, warp), 2, "float"), tileSizePx, 2, "float"), width=2)
        edgeDistPx = rt.binary("*", rt.component_wise("min", rt.component_wise("min", rt.swizzle(cellFrac, "x"), rt.binary("-", rt.f(1.0), rt.swizzle(cellFrac, "x"), 1, "float"), width=1), rt.component_wise("min", rt.swizzle(cellFrac, "y"), rt.binary("-", rt.f(1.0), rt.swizzle(cellFrac, "y"), 1, "float"), width=1), width=1), tileSizePx, 1, "float")
        groutHalfWidthPx = rt.binary("*", rt.binary("/", groutWidthPct, rt.f(100.0), 1, "float"), rt.binary("*", tileSizePx, rt.f(0.5), 1, "float"), 1, "float")
        groutAA = rt.f(1.25)
        return rt.binary("-", rt.f(1.0), rt.component_wise("smoothstep", rt.binary("-", groutHalfWidthPx, groutAA, 1, "float"), rt.binary("+", groutHalfWidthPx, groutAA, 1, "float"), edgeDistPx, width=1), 1, "float")
    def main__void():
        globalCoord = rt.binary("+", rt.swizzle(ctx.frag_coord, "xy"), _u_tileOffset, 2, "float")
        uv = rt.binary("/", rt.swizzle(ctx.frag_coord, "xy"), _u_resolution, 2, "float")
        srcHome = rt.texture(_u_inputTex, uv)
        seedF = rt.construct(1, _u_seed)
        result = rt.construct(3, 0.0)
        warp = rt.f(0.0)
        warpedCoord = rt.construct(2, 0.0)
        cellSpace = rt.construct(2, 0.0)
        cellId = rt.construct(2, 0.0)
        warpedCenter = rt.construct(2, 0.0)
        centerWarp = rt.f(0.0)
        sampleGc = rt.construct(2, 0.0)
        sampleUV = rt.construct(2, 0.0)
        tileColor = rt.construct(3, 0.0)
        kC = rt.f(0.0)
        kR = rt.f(0.0)
        kL = rt.f(0.0)
        kT = rt.f(0.0)
        kB = rt.f(0.0)
        gradK = rt.construct(2, 0.0)
        hC = rt.f(0.0)
        hR = rt.f(0.0)
        hT = rt.f(0.0)
        shadeStrength = rt.f(0.0)
        shade = rt.f(0.0)
        flatShade = rt.f(0.0)
        darkened = rt.construct(3, 0.0)
        shadeMul = rt.f(0.0)
        cellFrac = rt.construct(2, 0.0)
        edgeDistPx = rt.f(0.0)
        gapWidthPx = rt.f(0.0)
        gapAA = rt.f(0.0)
        gapMask = rt.f(0.0)
        offsetPx = rt.construct(2, 0.0)
        cellCenterGc = rt.construct(2, 0.0)
        shiftedGc = rt.construct(2, 0.0)
        shiftedUV = rt.construct(2, 0.0)
        gapColor = rt.construct(3, 0.0)
        if rt.binary("==", _u_MODE, rt.i(0)):
            warp = mosaicWarp__vec2_float_float(globalCoord, _u_tileSize, seedF)
            warpedCoord = rt.binary("+", globalCoord, rt.construct(2, warp), 2, "float")
            cellSpace = rt.binary("/", warpedCoord, _u_tileSize, 2, "float")
            cellId = rt.component_wise("floor", cellSpace, width=2)
            warpedCenter = rt.binary("*", rt.binary("+", cellId, rt.construct(2, rt.f(0.5)), 2, "float"), _u_tileSize, 2, "float")
            centerWarp = mosaicWarp__vec2_float_float(warpedCenter, _u_tileSize, seedF)
            sampleGc = rt.binary("-", warpedCenter, rt.construct(2, centerWarp), 2, "float")
            sampleUV = rt.component_wise("clamp", rt.binary("/", rt.binary("-", sampleGc, _u_tileOffset, 2, "float"), _u_resolution, 2, "float"), rt.f(0.0), rt.f(1.0), width=2)
            tileColor = rt.swizzle(rt.texture(_u_inputTex, sampleUV), "rgb")
            kC = mosaicGroutMask__vec2_float_float_float(globalCoord, _u_tileSize, _u_groutWidth, seedF)
            kR = mosaicGroutMask__vec2_float_float_float(rt.binary("+", globalCoord, rt.construct(2, rt.f(1.0), rt.f(0.0)), 2, "float"), _u_tileSize, _u_groutWidth, seedF)
            kL = mosaicGroutMask__vec2_float_float_float(rt.binary("-", globalCoord, rt.construct(2, rt.f(1.0), rt.f(0.0)), 2, "float"), _u_tileSize, _u_groutWidth, seedF)
            kT = mosaicGroutMask__vec2_float_float_float(rt.binary("+", globalCoord, rt.construct(2, rt.f(0.0), rt.f(1.0)), 2, "float"), _u_tileSize, _u_groutWidth, seedF)
            kB = mosaicGroutMask__vec2_float_float_float(rt.binary("-", globalCoord, rt.construct(2, rt.f(0.0), rt.f(1.0)), 2, "float"), _u_tileSize, _u_groutWidth, seedF)
            gradK = rt.construct(2, rt.binary("*", rt.binary("-", kR, kL, 1, "float"), rt.f(0.5), 1, "float"), rt.binary("*", rt.binary("-", kT, kB, 1, "float"), rt.f(0.5), 1, "float"))
            hC = rt.unary("-", kC)
            hR = rt.binary("-", hC, rt.swizzle(gradK, "x"), 1, "float")
            hT = rt.binary("-", hC, rt.swizzle(gradK, "y"), 1, "float")
            shadeStrength = rt.f(6.0)
            shade = reliefShade__float_float_float_float_float(hC, hR, hT, shadeStrength, rt.f(135.0))
            flatShade = rt.f(0.6)
            darkened = rt.binary("*", tileColor, rt.component_wise("mix", rt.f(1.0), rt.f(0.35), kC, width=1), 3, "float")
            shadeMul = rt.binary("+", rt.f(1.0), rt.binary("*", rt.binary("*", rt.binary("-", shade, flatShade, 1, "float"), rt.f(2.0), 1, "float"), rt.binary("/", _u_relief, rt.f(100.0), 1, "float"), 1, "float"), 1, "float")
            result[:] = rt.component_wise("clamp", rt.binary("*", darkened, shadeMul, 3, "float"), rt.f(0.0), rt.f(1.0), width=3)
        else:
            if rt.binary("==", _u_MODE, rt.i(1)):
                cellSpace = rt.binary("/", globalCoord, _u_tileSize, 2, "float")
                cellId = rt.component_wise("floor", cellSpace, width=2)
                cellFrac = rt.component_wise("fract", cellSpace, width=2)
                edgeDistPx = rt.binary("*", rt.component_wise("min", rt.component_wise("min", rt.swizzle(cellFrac, "x"), rt.binary("-", rt.f(1.0), rt.swizzle(cellFrac, "x"), 1, "float"), width=1), rt.component_wise("min", rt.swizzle(cellFrac, "y"), rt.binary("-", rt.f(1.0), rt.swizzle(cellFrac, "y"), 1, "float"), width=1), width=1), _u_tileSize, 1, "float")
                gapWidthPx = rt.binary("*", rt.binary("/", _u_groutWidth, rt.f(100.0), 1, "float"), _u_tileSize, 1, "float")
                gapAA = rt.f(1.25)
                gapMask = rt.binary("-", rt.f(1.0), rt.component_wise("smoothstep", rt.binary("-", rt.binary("*", gapWidthPx, rt.f(0.5), 1, "float"), gapAA, 1, "float"), rt.binary("+", rt.binary("*", gapWidthPx, rt.f(0.5), 1, "float"), gapAA, 1, "float"), edgeDistPx, width=1), 1, "float")
                offsetPx = rt.binary("*", rt.binary("*", rt.binary("*", rt.binary("-", hash22__vec2(rt.binary("+", cellId, rt.binary("*", seedF, rt.f(101.7), 1, "float"), 2, "float")), rt.f(0.5), 2, "float"), rt.f(2.0), 2, "float"), rt.binary("/", _u_maxOffset, rt.f(100.0), 1, "float"), 2, "float"), _u_tileSize, 2, "float")
                cellCenterGc = rt.binary("*", rt.binary("+", cellId, rt.construct(2, rt.f(0.5)), 2, "float"), _u_tileSize, 2, "float")
                shiftedGc = rt.binary("+", cellCenterGc, offsetPx, 2, "float")
                shiftedUV = rt.component_wise("clamp", rt.binary("/", rt.binary("-", shiftedGc, _u_tileOffset, 2, "float"), _u_resolution, 2, "float"), rt.f(0.0), rt.f(1.0), width=2)
                tileColor = rt.swizzle(rt.texture(_u_inputTex, shiftedUV), "rgb")
                gapColor = rt.construct(3, 0.0)
                if rt.binary("==", _u_gapFill, rt.i(0)):
                    gapColor[:] = _u_backgroundColor
                else:
                    if rt.binary("==", _u_gapFill, rt.i(1)):
                        gapColor[:] = rt.binary("-", rt.f(1.0), rt.swizzle(srcHome, "rgb"), 3, "float")
                    else:
                        gapColor[:] = rt.swizzle(srcHome, "rgb")
                result[:] = rt.component_wise("mix", tileColor, gapColor, gapMask, width=3)
        g.fragColor[:] = rt.construct(4, result, rt.swizzle(srcHome, "a"))
    main__void()
    _c = g.fragColor
    out[0] = rt.f32(_c[0]); out[1] = rt.f32(_c[1]); out[2] = rt.f32(_c[2]); out[3] = rt.f32(_c[3])
