def run_pixel(ctx, out):
    rt = ctx.rt
    U = ctx.uniforms
    T = ctx.textures
    class _G:
        pass
    g = _G()
    _u_inputTex = T["inputTex"]
    _u_resolution = U.get("resolution", rt.construct(2, 0.0))
    _u_detail = U.get("detail", rt.f(0.0))
    g.fragColor = rt.construct(4, 0.0)
    def sort2__vec3_vec3(a, b):
        a = rt.copy(a, "float")
        b = rt.copy(b, "float")
        lo = rt.component_wise("min", a, b, width=3)
        hi = rt.component_wise("max", a, b, width=3)
        a[:] = lo
        b[:] = hi
        return (None, a, b)
    def main__void():
        stride = rt.component_wise("mix", rt.f(3.0), rt.f(1.0), rt.binary("/", rt.component_wise("clamp", _u_detail, rt.f(0.0), rt.f(100.0), width=1), rt.f(100.0), 1, "float"), width=1)
        texel = rt.binary("/", stride, _u_resolution, 2, "float")
        uv = rt.binary("/", rt.swizzle(ctx.frag_coord, "xy"), _u_resolution, 2, "float")
        s0 = rt.texture(_u_inputTex, rt.binary("+", uv, rt.construct(2, rt.unary("-", rt.swizzle(texel, "x")), rt.unary("-", rt.swizzle(texel, "y"))), 2, "float"))
        s1 = rt.texture(_u_inputTex, rt.binary("+", uv, rt.construct(2, rt.f(0.0), rt.unary("-", rt.swizzle(texel, "y"))), 2, "float"))
        s2 = rt.texture(_u_inputTex, rt.binary("+", uv, rt.construct(2, rt.swizzle(texel, "x"), rt.unary("-", rt.swizzle(texel, "y"))), 2, "float"))
        s3 = rt.texture(_u_inputTex, rt.binary("+", uv, rt.construct(2, rt.unary("-", rt.swizzle(texel, "x")), rt.f(0.0)), 2, "float"))
        s4 = rt.texture(_u_inputTex, uv)
        s5 = rt.texture(_u_inputTex, rt.binary("+", uv, rt.construct(2, rt.swizzle(texel, "x"), rt.f(0.0)), 2, "float"))
        s6 = rt.texture(_u_inputTex, rt.binary("+", uv, rt.construct(2, rt.unary("-", rt.swizzle(texel, "x")), rt.swizzle(texel, "y")), 2, "float"))
        s7 = rt.texture(_u_inputTex, rt.binary("+", uv, rt.construct(2, rt.f(0.0), rt.swizzle(texel, "y")), 2, "float"))
        s8 = rt.texture(_u_inputTex, rt.binary("+", uv, rt.construct(2, rt.swizzle(texel, "x"), rt.swizzle(texel, "y")), 2, "float"))
        p0 = rt.swizzle(s0, "rgb")
        p1 = rt.swizzle(s1, "rgb")
        p2 = rt.swizzle(s2, "rgb")
        p3 = rt.swizzle(s3, "rgb")
        p4 = rt.swizzle(s4, "rgb")
        p5 = rt.swizzle(s5, "rgb")
        p6 = rt.swizzle(s6, "rgb")
        p7 = rt.swizzle(s7, "rgb")
        p8 = rt.swizzle(s8, "rgb")
        (((_retc0 := sort2__vec3_vec3(p1, p2)), p1.__setitem__(slice(None), _retc0[1]), p2.__setitem__(slice(None), _retc0[2]), _retc0[0])[-1])
        (((_retc1 := sort2__vec3_vec3(p4, p5)), p4.__setitem__(slice(None), _retc1[1]), p5.__setitem__(slice(None), _retc1[2]), _retc1[0])[-1])
        (((_retc2 := sort2__vec3_vec3(p7, p8)), p7.__setitem__(slice(None), _retc2[1]), p8.__setitem__(slice(None), _retc2[2]), _retc2[0])[-1])
        (((_retc3 := sort2__vec3_vec3(p0, p1)), p0.__setitem__(slice(None), _retc3[1]), p1.__setitem__(slice(None), _retc3[2]), _retc3[0])[-1])
        (((_retc4 := sort2__vec3_vec3(p3, p4)), p3.__setitem__(slice(None), _retc4[1]), p4.__setitem__(slice(None), _retc4[2]), _retc4[0])[-1])
        (((_retc5 := sort2__vec3_vec3(p6, p7)), p6.__setitem__(slice(None), _retc5[1]), p7.__setitem__(slice(None), _retc5[2]), _retc5[0])[-1])
        (((_retc6 := sort2__vec3_vec3(p1, p2)), p1.__setitem__(slice(None), _retc6[1]), p2.__setitem__(slice(None), _retc6[2]), _retc6[0])[-1])
        (((_retc7 := sort2__vec3_vec3(p4, p5)), p4.__setitem__(slice(None), _retc7[1]), p5.__setitem__(slice(None), _retc7[2]), _retc7[0])[-1])
        (((_retc8 := sort2__vec3_vec3(p7, p8)), p7.__setitem__(slice(None), _retc8[1]), p8.__setitem__(slice(None), _retc8[2]), _retc8[0])[-1])
        (((_retc9 := sort2__vec3_vec3(p0, p3)), p0.__setitem__(slice(None), _retc9[1]), p3.__setitem__(slice(None), _retc9[2]), _retc9[0])[-1])
        (((_retc10 := sort2__vec3_vec3(p5, p8)), p5.__setitem__(slice(None), _retc10[1]), p8.__setitem__(slice(None), _retc10[2]), _retc10[0])[-1])
        (((_retc11 := sort2__vec3_vec3(p4, p7)), p4.__setitem__(slice(None), _retc11[1]), p7.__setitem__(slice(None), _retc11[2]), _retc11[0])[-1])
        (((_retc12 := sort2__vec3_vec3(p3, p6)), p3.__setitem__(slice(None), _retc12[1]), p6.__setitem__(slice(None), _retc12[2]), _retc12[0])[-1])
        (((_retc13 := sort2__vec3_vec3(p1, p4)), p1.__setitem__(slice(None), _retc13[1]), p4.__setitem__(slice(None), _retc13[2]), _retc13[0])[-1])
        (((_retc14 := sort2__vec3_vec3(p2, p5)), p2.__setitem__(slice(None), _retc14[1]), p5.__setitem__(slice(None), _retc14[2]), _retc14[0])[-1])
        (((_retc15 := sort2__vec3_vec3(p4, p7)), p4.__setitem__(slice(None), _retc15[1]), p7.__setitem__(slice(None), _retc15[2]), _retc15[0])[-1])
        (((_retc16 := sort2__vec3_vec3(p4, p2)), p4.__setitem__(slice(None), _retc16[1]), p2.__setitem__(slice(None), _retc16[2]), _retc16[0])[-1])
        (((_retc17 := sort2__vec3_vec3(p6, p4)), p6.__setitem__(slice(None), _retc17[1]), p4.__setitem__(slice(None), _retc17[2]), _retc17[0])[-1])
        (((_retc18 := sort2__vec3_vec3(p4, p2)), p4.__setitem__(slice(None), _retc18[1]), p2.__setitem__(slice(None), _retc18[2]), _retc18[0])[-1])
        g.fragColor[:] = rt.construct(4, p4, rt.swizzle(s4, "a"))
    main__void()
    _c = g.fragColor
    out[0] = rt.f32(_c[0]); out[1] = rt.f32(_c[1]); out[2] = rt.f32(_c[2]); out[3] = rt.f32(_c[3])
run_pixel.output_names = ('fragColor',)
