def run_pixel(ctx, out):
    rt = ctx.rt
    U = ctx.uniforms
    T = ctx.textures
    class _G:
        pass
    g = _G()
    _u_OCTAVES = U.get("OCTAVES", 0)
    _u_COLOR_MODE = U.get("COLOR_MODE", 0)
    _u_RIDGES = U.get("RIDGES", 0)
    _u_tileOffset = U.get("tileOffset", rt.construct(2, 0.0))
    _u_fullResolution = U.get("fullResolution", rt.construct(2, 0.0))
    _u_time = U.get("time", rt.f(0.0))
    _u_scale = U.get("scale", rt.f(0.0))
    _u_seed = U.get("seed", 0)
    _u_volumeSize = U.get("volumeSize", 0)
    _u_speed = U.get("speed", rt.f(0.0))
    g.fragColor = rt.construct(4, 0.0)
    g.geoOut = rt.construct(4, 0.0)
    g.TAU = rt.f(6.283185307179586)
    g.W_PERIOD = rt.f(4.0)
    def hash4__vec4(p):
        p = rt.copy(p, "float")
        ps = rt.construct(4, rt.binary("+", p, rt.binary("*", rt.construct(1, _u_seed), rt.f(0.1), 1, "float"), 4, "float"))
        q = rt.construct(4, rt.binary("+", rt.construct(4, rt.construct(4, rt.binary("*", ps, rt.f(1000.0), 4, "float")), base="int"), rt.i(65536), 4, "int"), base="uint")
        q[:] = rt.binary("+", rt.binary("*", q, rt.i(1664525), 4, "uint"), rt.i(1013904223), 4, "uint")
        q = rt.assign_swizzle(q, "x", rt.binary("+", rt.swizzle(q, "x"), rt.binary("*", rt.swizzle(q, "y"), rt.swizzle(q, "z"), 1, "uint"), 1, "uint"))
        q = rt.assign_swizzle(q, "y", rt.binary("+", rt.swizzle(q, "y"), rt.binary("*", rt.swizzle(q, "z"), rt.swizzle(q, "w"), 1, "uint"), 1, "uint"))
        q = rt.assign_swizzle(q, "z", rt.binary("+", rt.swizzle(q, "z"), rt.binary("*", rt.swizzle(q, "w"), rt.swizzle(q, "x"), 1, "uint"), 1, "uint"))
        q = rt.assign_swizzle(q, "w", rt.binary("+", rt.swizzle(q, "w"), rt.binary("*", rt.swizzle(q, "x"), rt.swizzle(q, "y"), 1, "uint"), 1, "uint"))
        q[:] = rt.binary("^", q, rt.binary(">>", q, rt.i(16), 4, "uint"), 4, "uint")
        q = rt.assign_swizzle(q, "x", rt.binary("+", rt.swizzle(q, "x"), rt.binary("*", rt.swizzle(q, "y"), rt.swizzle(q, "z"), 1, "uint"), 1, "uint"))
        q = rt.assign_swizzle(q, "y", rt.binary("+", rt.swizzle(q, "y"), rt.binary("*", rt.swizzle(q, "z"), rt.swizzle(q, "w"), 1, "uint"), 1, "uint"))
        q = rt.assign_swizzle(q, "z", rt.binary("+", rt.swizzle(q, "z"), rt.binary("*", rt.swizzle(q, "w"), rt.swizzle(q, "x"), 1, "uint"), 1, "uint"))
        q = rt.assign_swizzle(q, "w", rt.binary("+", rt.swizzle(q, "w"), rt.binary("*", rt.swizzle(q, "x"), rt.swizzle(q, "y"), 1, "uint"), 1, "uint"))
        return rt.binary("/", rt.construct(1, rt.binary("^", rt.binary("^", rt.binary("^", rt.swizzle(q, "x"), rt.swizzle(q, "y"), 1, "uint"), rt.swizzle(q, "z"), 1, "uint"), rt.swizzle(q, "w"), 1, "uint")), rt.f(4294967295.0), 1, "float")
    def grad4__vec4(p):
        p = rt.copy(p, "float")
        h1 = hash4__vec4(p)
        h2 = hash4__vec4(rt.binary("+", p, rt.f(127.1), 4, "float"))
        h3 = hash4__vec4(rt.binary("+", p, rt.f(269.5), 4, "float"))
        h4 = hash4__vec4(rt.binary("+", p, rt.f(419.2), 4, "float"))
        _g = rt.construct(4, rt.binary("-", rt.binary("*", h1, rt.f(2.0), 1, "float"), rt.f(1.0), 1, "float"), rt.binary("-", rt.binary("*", h2, rt.f(2.0), 1, "float"), rt.f(1.0), 1, "float"), rt.binary("-", rt.binary("*", h3, rt.f(2.0), 1, "float"), rt.f(1.0), 1, "float"), rt.binary("-", rt.binary("*", h4, rt.f(2.0), 1, "float"), rt.f(1.0), 1, "float"))
        return rt.normalize(_g)
    def quintic__float(t):
        return rt.binary("*", rt.binary("*", rt.binary("*", t, t, 1, "float"), t, 1, "float"), rt.binary("+", rt.binary("*", t, rt.binary("-", rt.binary("*", t, rt.f(6.0), 1, "float"), rt.f(15.0), 1, "float"), 1, "float"), rt.f(10.0), 1, "float"), 1, "float")
    def wrapW__float(w):
        return rt.component_wise("mod", w, g.W_PERIOD, width=1)
    def noise4D__vec4(p):
        p = rt.copy(p, "float")
        i = rt.component_wise("floor", p, width=4)
        f = rt.component_wise("fract", p, width=4)
        u = rt.construct(4, quintic__float(rt.swizzle(f, "x")), quintic__float(rt.swizzle(f, "y")), quintic__float(rt.swizzle(f, "z")), quintic__float(rt.swizzle(f, "w")))
        iw0 = wrapW__float(rt.swizzle(i, "w"))
        iw1 = wrapW__float(rt.binary("+", rt.swizzle(i, "w"), rt.f(1.0), 1, "float"))
        n0000 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw0), rt.construct(4, rt.i(0), rt.i(0), rt.i(0), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(0), rt.i(0), rt.i(0), rt.i(0)), 4, "float"))
        n1000 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw0), rt.construct(4, rt.i(1), rt.i(0), rt.i(0), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(1), rt.i(0), rt.i(0), rt.i(0)), 4, "float"))
        n0100 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw0), rt.construct(4, rt.i(0), rt.i(1), rt.i(0), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(0), rt.i(1), rt.i(0), rt.i(0)), 4, "float"))
        n1100 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw0), rt.construct(4, rt.i(1), rt.i(1), rt.i(0), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(1), rt.i(1), rt.i(0), rt.i(0)), 4, "float"))
        n0010 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw0), rt.construct(4, rt.i(0), rt.i(0), rt.i(1), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(0), rt.i(0), rt.i(1), rt.i(0)), 4, "float"))
        n1010 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw0), rt.construct(4, rt.i(1), rt.i(0), rt.i(1), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(1), rt.i(0), rt.i(1), rt.i(0)), 4, "float"))
        n0110 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw0), rt.construct(4, rt.i(0), rt.i(1), rt.i(1), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(0), rt.i(1), rt.i(1), rt.i(0)), 4, "float"))
        n1110 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw0), rt.construct(4, rt.i(1), rt.i(1), rt.i(1), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(1), rt.i(1), rt.i(1), rt.i(0)), 4, "float"))
        n0001 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw1), rt.construct(4, rt.i(0), rt.i(0), rt.i(0), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(0), rt.i(0), rt.i(0), rt.i(1)), 4, "float"))
        n1001 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw1), rt.construct(4, rt.i(1), rt.i(0), rt.i(0), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(1), rt.i(0), rt.i(0), rt.i(1)), 4, "float"))
        n0101 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw1), rt.construct(4, rt.i(0), rt.i(1), rt.i(0), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(0), rt.i(1), rt.i(0), rt.i(1)), 4, "float"))
        n1101 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw1), rt.construct(4, rt.i(1), rt.i(1), rt.i(0), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(1), rt.i(1), rt.i(0), rt.i(1)), 4, "float"))
        n0011 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw1), rt.construct(4, rt.i(0), rt.i(0), rt.i(1), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(0), rt.i(0), rt.i(1), rt.i(1)), 4, "float"))
        n1011 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw1), rt.construct(4, rt.i(1), rt.i(0), rt.i(1), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(1), rt.i(0), rt.i(1), rt.i(1)), 4, "float"))
        n0111 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw1), rt.construct(4, rt.i(0), rt.i(1), rt.i(1), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(0), rt.i(1), rt.i(1), rt.i(1)), 4, "float"))
        n1111 = rt.dot(grad4__vec4(rt.binary("+", rt.construct(4, rt.swizzle(i, "xyz"), iw1), rt.construct(4, rt.i(1), rt.i(1), rt.i(1), rt.i(0)), 4, "float")), rt.binary("-", f, rt.construct(4, rt.i(1), rt.i(1), rt.i(1), rt.i(1)), 4, "float"))
        nx000 = rt.component_wise("mix", n0000, n1000, rt.swizzle(u, "x"), width=1)
        nx100 = rt.component_wise("mix", n0100, n1100, rt.swizzle(u, "x"), width=1)
        nx010 = rt.component_wise("mix", n0010, n1010, rt.swizzle(u, "x"), width=1)
        nx110 = rt.component_wise("mix", n0110, n1110, rt.swizzle(u, "x"), width=1)
        nx001 = rt.component_wise("mix", n0001, n1001, rt.swizzle(u, "x"), width=1)
        nx101 = rt.component_wise("mix", n0101, n1101, rt.swizzle(u, "x"), width=1)
        nx011 = rt.component_wise("mix", n0011, n1011, rt.swizzle(u, "x"), width=1)
        nx111 = rt.component_wise("mix", n0111, n1111, rt.swizzle(u, "x"), width=1)
        nxy00 = rt.component_wise("mix", nx000, nx100, rt.swizzle(u, "y"), width=1)
        nxy10 = rt.component_wise("mix", nx010, nx110, rt.swizzle(u, "y"), width=1)
        nxy01 = rt.component_wise("mix", nx001, nx101, rt.swizzle(u, "y"), width=1)
        nxy11 = rt.component_wise("mix", nx011, nx111, rt.swizzle(u, "y"), width=1)
        nxyz0 = rt.component_wise("mix", nxy00, nxy10, rt.swizzle(u, "z"), width=1)
        nxyz1 = rt.component_wise("mix", nxy01, nxy11, rt.swizzle(u, "z"), width=1)
        return rt.component_wise("mix", nxyz0, nxyz1, rt.swizzle(u, "w"), width=1)
    def fbm4D__vec4(p):
        p = rt.copy(p, "float")
        amplitude = rt.f(0.5)
        frequency = rt.f(1.0)
        sum = rt.f(0.0)
        maxVal = rt.f(0.0)
        i = rt.i(0)
        _for0_first = True
        for _for0 in range(1048576):
            if not _for0_first:
                i = rt.binary("+", i, rt.i(1), 1, "int")
            _for0_first = False
            if not (rt.binary("<", i, _u_OCTAVES)):
                break
            pos = rt.construct(4, rt.binary("*", rt.swizzle(p, "xyz"), frequency, 3, "float"), rt.swizzle(p, "w"))
            n = noise4D__vec4(pos)
            n = rt.component_wise("clamp", rt.binary("*", n, rt.f(1.5), 1, "float"), rt.unary("-", rt.f(1.0)), rt.f(1.0), width=1)
            if _u_RIDGES:
                n = rt.binary("-", rt.f(1.0), rt.component_wise("abs", n, width=1), 1, "float")
            else:
                n = rt.binary("*", rt.binary("+", n, rt.f(1.0), 1, "float"), rt.f(0.5), 1, "float")
            sum = rt.binary("+", sum, rt.binary("*", n, amplitude, 1, "float"), 1, "float")
            maxVal = rt.binary("+", maxVal, amplitude, 1, "float")
            frequency = rt.binary("*", frequency, rt.f(2.0), 1, "float")
            amplitude = rt.binary("*", amplitude, rt.f(0.5), 1, "float")
        return rt.binary("/", sum, maxVal, 1, "float")
    def main__void():
        globalCoord = rt.construct(2, rt.binary("+", rt.swizzle(ctx.frag_coord, "xy"), _u_tileOffset, 2, "float"))
        volSize = _u_volumeSize
        volSizeF = rt.construct(1, volSize)
        pixelCoord = rt.construct(2, rt.swizzle(ctx.frag_coord, "xy"), base="int")
        x = rt.swizzle(pixelCoord, "x")
        y = rt.binary("%", rt.swizzle(pixelCoord, "y"), volSize, 1, "int")
        z = rt.binary("/", rt.swizzle(pixelCoord, "y"), volSize, 1, "int")
        if (bool((bool(rt.binary(">=", x, volSize)) or bool(rt.binary(">=", y, volSize)))) or bool(rt.binary(">=", z, volSize))):
            g.fragColor[:] = rt.construct(4, rt.f(0.0))
            g.geoOut[:] = rt.construct(4, rt.f(0.5), rt.f(0.5), rt.f(0.5), rt.f(0.0))
            return
        p = rt.construct(3, rt.binary("-", rt.binary("*", rt.binary("/", rt.construct(3, rt.construct(1, x), rt.construct(1, y), rt.construct(1, z)), rt.binary("-", volSizeF, rt.f(1.0), 1, "float"), 3, "float"), rt.f(2.0), 3, "float"), rt.f(1.0), 3, "float"))
        scaledP = rt.construct(3, rt.binary("*", p, _u_scale, 3, "float"))
        w = rt.binary("*", rt.binary("*", _u_time, _u_speed, 1, "float"), g.W_PERIOD, 1, "float")
        p4d = rt.construct(4, scaledP, w)
        noiseVal = fbm4D__vec4(p4d)
        eps = rt.binary("/", rt.f(0.01), _u_scale, 1, "float")
        nx = fbm4D__vec4(rt.construct(4, rt.binary("+", scaledP, rt.construct(3, eps, rt.f(0.0), rt.f(0.0)), 3, "float"), w))
        ny = fbm4D__vec4(rt.construct(4, rt.binary("+", scaledP, rt.construct(3, rt.f(0.0), eps, rt.f(0.0)), 3, "float"), w))
        nz = fbm4D__vec4(rt.construct(4, rt.binary("+", scaledP, rt.construct(3, rt.f(0.0), rt.f(0.0), eps), 3, "float"), w))
        gradient = rt.construct(3, rt.binary("/", rt.construct(3, rt.binary("-", nx, noiseVal, 1, "float"), rt.binary("-", ny, noiseVal, 1, "float"), rt.binary("-", nz, noiseVal, 1, "float")), eps, 3, "float"))
        normal = rt.normalize(rt.binary("+", rt.unary("-", gradient), rt.construct(3, rt.f(1e-06)), 3, "float"))
        _g = rt.f(0.0)
        b = rt.f(0.0)
        if rt.binary("==", _u_COLOR_MODE, rt.i(0)):
            g.fragColor[:] = rt.construct(4, noiseVal, noiseVal, noiseVal, rt.f(1.0))
        else:
            _g = fbm4D__vec4(rt.binary("+", rt.construct(4, scaledP, w), rt.construct(4, rt.f(0.0), rt.f(0.0), rt.f(0.0), rt.f(1.33)), 4, "float"))
            b = fbm4D__vec4(rt.binary("+", rt.construct(4, scaledP, w), rt.construct(4, rt.f(0.0), rt.f(0.0), rt.f(0.0), rt.f(2.67)), 4, "float"))
            g.fragColor[:] = rt.construct(4, noiseVal, _g, b, rt.f(1.0))
        g.geoOut[:] = rt.construct(4, rt.binary("+", rt.binary("*", normal, rt.f(0.5), 3, "float"), rt.f(0.5), 3, "float"), noiseVal)
    main__void()
    _c = g.fragColor
    out[0][0] = rt.f32(_c[0]); out[0][1] = rt.f32(_c[1]); out[0][2] = rt.f32(_c[2]); out[0][3] = rt.f32(_c[3])
    _c = g.geoOut
    out[1][0] = rt.f32(_c[0]); out[1][1] = rt.f32(_c[1]); out[1][2] = rt.f32(_c[2]); out[1][3] = rt.f32(_c[3])
run_pixel.output_names = ('fragColor', 'geoOut')
