"""Node-free parity receipt: replays scripts/parity.py's recorded byte-exact
comparisons against the committed receipt without a JS oracle.

The receipt (tests/data/parity-receipt-<revision>.json) is generated by
``scripts/parity.py --json`` against a sibling noisemaker-for-cpu checkout at
the recorded revision; each entry stores the sha256 of the oracle's PNG bytes
and of this port's PNG bytes, which were verified byte-identical at
generation time. This test re-renders the Python side and asserts the recorded
hashes still match, so a renderer or bundle change that breaks byte parity with
the pinned -cpu oracle fails here without needing node or the sibling
checkout.
"""

import hashlib
import importlib.util
import json
import os
from pathlib import Path

import pytest

RECEIPT = Path(__file__).parent / "data" / "parity-receipt-8eeb7b5a.json"

spec = importlib.util.spec_from_file_location("parity_harness", Path(__file__).parents[1] / "scripts" / "parity.py")
parity_harness = importlib.util.module_from_spec(spec)
spec.loader.exec_module(parity_harness)


def test_receipt_binds_the_pinned_cpu_revision():
    doc = json.loads(RECEIPT.read_text(encoding="utf-8"))
    assert doc["cpu"]["revision"] == "8eeb7b5ac14eb37a8d16037f607a88ce63924cd3"
    assert doc["cpu"]["sourceDigest"] == "ceeccdd13b7b625b94c58dcfa318b4a253d5dc6d124e551233522fd5f32e399b"
    assert doc["cpu"]["cpuHead"] == "bfbe54764eee87c8f67d2b281d5f304faad04a5b"
    assert doc["settings"] == {"size": 8, "seed": 1, "time": 0.25, "tolerance": 0}
    assert doc["counts"]["diffs"] == 0
    assert doc["counts"]["runtimeErrors"] == 0
    assert doc["counts"]["oracleErrors"] == 0


def test_receipt_covers_the_full_noniterated_image_catalog():
    doc = json.loads(RECEIPT.read_text(encoding="utf-8"))
    effects = parity_harness._meta()["effects"]
    eligible = [
        i
        for i in effects
        if not (effects[i].get("iterated") or effects[i].get("domain", "image") != "image")
    ]
    assert sorted(doc["byteExact"]) == sorted(eligible), (
        "receipt must cover every eligible non-iterated image effect; regenerate with scripts/parity.py --json"
    )


def test_python_renders_match_the_recorded_oracle_hashes():
    doc = json.loads(RECEIPT.read_text(encoding="utf-8"))
    effects = parity_harness._meta()["effects"]
    for eid, entry in sorted(doc["byteExact"].items()):
        kind = effects[eid]["kind"]
        ext = effects[eid].get("externalTexture")
        py = parity_harness.py_render(eid, kind, ext)
        sha = hashlib.sha256(py.to_rgba8()).hexdigest()
        assert sha == entry["pythonRgba8Sha256"] == entry["oracleRgba8Sha256"], (
            f"{eid} no longer matches the pinned -cpu oracle output recorded in {RECEIPT.name}"
        )


def test_receipt_is_current_when_the_oracle_is_available():
    """If the sibling -cpu checkout at the pinned revision and node are present,
    regenerate the receipt and require it to be unchanged. Otherwise skip."""
    cli = parity_harness.CLI
    doc = json.loads(RECEIPT.read_text(encoding="utf-8"))
    try:
        lock = parity_harness._cpu_revision()
    except OSError:
        lock = {}
    has_oracle = os.path.exists(cli) and lock.get("revision") == doc["cpu"]["revision"]
    if not has_oracle:
        pytest.skip(f"oracle checkout at {doc['cpu']['revision'][:7]} not available")
    import subprocess
    import sys
    import tempfile

    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tmp:
        tmp_path = tmp.name
    env = dict(os.environ)
    env["PYTHONPATH"] = str(Path(__file__).parents[1] / "src") + os.pathsep + env.get("PYTHONPATH", "")
    result = subprocess.run(
        [sys.executable, str(Path(__file__).parents[1] / "scripts" / "parity.py"), "--json", tmp_path],
        capture_output=True,
        text=True,
        cwd=str(Path(__file__).parents[1]),
        env=env,
    )
    fresh = json.loads(Path(tmp_path).read_text(encoding="utf-8"))
    assert fresh["byteExact"] == doc["byteExact"], (
        "regenerated receipt differs from the committed receipt; run scripts/parity.py --json and commit the refresh"
    )
    assert result.returncode == 0
