"""Node-free parity receipt: replays scripts/parity.py's recorded byte-exact
comparisons against the committed receipt without a JS oracle.

The receipt (tests/data/parity-receipt-<revision>.json) is generated by
``scripts/parity.py --json`` against a sibling noisemaker-for-cpu checkout at
the recorded revision; each entry stores the sha256 of the oracle's PNG bytes
and of this port's PNG bytes, which were verified byte-identical at
generation time. This test re-renders the Python side and asserts the recorded
hashes still match, so a renderer or bundle change that breaks byte parity with
the pinned -cpu oracle fails here without needing node or the sibling
checkout.
"""

import hashlib
import importlib.util
import json
import os
from pathlib import Path

import pytest

RECEIPT = Path(__file__).parent / "data" / "parity-receipt-296e0138.json"

spec = importlib.util.spec_from_file_location("parity_harness", Path(__file__).parents[1] / "scripts" / "parity.py")
parity_harness = importlib.util.module_from_spec(spec)
spec.loader.exec_module(parity_harness)


def test_receipt_binds_the_pinned_cpu_revision():
    doc = json.loads(RECEIPT.read_text(encoding="utf-8"))
    assert doc["cpu"]["revision"] == "296e0138c4744ed485b2e95de3eeb466c17629ee"
    assert doc["cpu"]["sourceDigest"] == "e371a1650d1ace9462a20ecf4e4f0902e5135b4772e8a9abbc8d2c037beebf59"
    assert doc["cpu"]["cpuHead"] == "b61b658399f18b5a93abd0020c02fff3be9630f5"
    assert doc["settings"] == {"size": 8, "seed": 1, "time": 0.25, "tolerance": 0}
    assert doc["counts"]["diffs"] == 0
    assert doc["counts"]["runtimeErrors"] == 0
    assert doc["counts"]["oracleErrors"] == 0


def test_receipt_covers_the_full_noniterated_image_catalog():
    doc = json.loads(RECEIPT.read_text(encoding="utf-8"))
    effects = parity_harness._meta()["effects"]
    eligible = [
        i
        for i in effects
        if not (effects[i].get("iterated") or effects[i].get("domain", "image") != "image")
    ]
    assert sorted(doc["byteExact"]) == sorted(eligible), (
        "receipt must cover every eligible non-iterated image effect; regenerate with scripts/parity.py --json"
    )


def test_python_renders_match_the_recorded_oracle_hashes():
    doc = json.loads(RECEIPT.read_text(encoding="utf-8"))
    effects = parity_harness._meta()["effects"]
    for eid, entry in sorted(doc["byteExact"].items()):
        kind = effects[eid]["kind"]
        ext = effects[eid].get("externalTexture")
        py = parity_harness.py_render(eid, kind, ext)
        sha = hashlib.sha256(py.to_rgba8()).hexdigest()
        assert sha == entry["pythonRgba8Sha256"] == entry["oracleRgba8Sha256"], (
            f"{eid} no longer matches the pinned -cpu oracle output recorded in {RECEIPT.name}"
        )


def test_receipt_is_current_when_the_oracle_is_available():
    """If the sibling -cpu checkout at the pinned revision and node are present,
    regenerate the receipt and require it to be unchanged. Otherwise skip."""
    cli = parity_harness.CLI
    doc = json.loads(RECEIPT.read_text(encoding="utf-8"))
    try:
        lock = parity_harness._cpu_revision()
    except OSError:
        lock = {}
    has_oracle = os.path.exists(cli) and lock.get("revision") == doc["cpu"]["revision"]
    if not has_oracle:
        pytest.skip(f"oracle checkout at {doc['cpu']['revision'][:7]} not available")
    import subprocess
    import sys
    import tempfile

    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as tmp:
        tmp_path = tmp.name
    env = dict(os.environ)
    env["PYTHONPATH"] = str(Path(__file__).parents[1] / "src") + os.pathsep + env.get("PYTHONPATH", "")
    result = subprocess.run(
        [sys.executable, str(Path(__file__).parents[1] / "scripts" / "parity.py"), "--json", tmp_path],
        capture_output=True,
        text=True,
        cwd=str(Path(__file__).parents[1]),
        env=env,
    )
    fresh = json.loads(Path(tmp_path).read_text(encoding="utf-8"))
    assert fresh["byteExact"].keys() == doc["byteExact"].keys()
    # Node's zlib output can differ across platforms while decoding to identical
    # pixels. Keep its PNG hash as provenance; compare exact RGBA8 on both sides
    # and the port's deterministic PNG bytes against the committed receipt.
    for effect_id, expected in doc["byteExact"].items():
        for key in ("oracleRgba8Sha256", "pythonRgba8Sha256", "pythonPngSha256"):
            assert fresh["byteExact"][effect_id][key] == expected[key], (effect_id, key)
    assert result.returncode == 0


def test_parity_scratch_is_isolated_and_uses_platform_temp(tmp_path):
    import subprocess
    import sys

    script = str(Path(__file__).parents[1] / 'scripts/parity.py')
    probe = f'''import json, pathlib, runpy
scope = runpy.run_path({script!r})
paths = [scope['EXT_PNG'], scope['JS_PNG']]
for name in paths:
    pathlib.Path(name).write_bytes(b'probe')
print(json.dumps(paths))
'''
    env = dict(os.environ, TMPDIR=str(tmp_path), TEMP=str(tmp_path), TMP=str(tmp_path))
    results = []
    for _ in range(2):
        result = subprocess.run([sys.executable, '-c', probe], env=env, capture_output=True, text=True, check=True)
        paths = [Path(p) for p in json.loads(result.stdout)]
        assert all(p.is_relative_to(tmp_path) for p in paths)
        assert all(not p.exists() for p in paths), 'Scratch files must be removed on exit'
        results.append(paths)
    assert set(results[0]).isdisjoint(results[1]), 'Concurrent runs must not share oracle output paths'
